### ISSUE TITLE
[best practices improvements] Use fetch instead of XMLHttpRequest and $.ajax

### ISSUE THREAD

**Issue by ThomasG77** [uwcartlab/webcartography#21]
Only point of XMLHttpRequest is that were AJAX name comes from.

Example 2.2 (https://github.com/uwcartlab/webmapping/blob/master/Chapter03/readme.md#example-22-creating-an-ajax-event-handler-that-calls-a-callback-function-inmainjs) can be replaced by the following

```
function callback(response){
    //tasks using the data go here
    console.log(response);
};

fetch('data/MegaCities.geojson').then(res => res.json()).then(callback)
```

Use `fetch` instead of jQuery to make ajax calls. It avoids adding another syntax to learn. Students, hence learn only one syntax. Fetch samples can be seen at https://github.com/mdn/fetch-examples

Both `XMLHttpRequest` and `$.ajax` should be thrown away. It's only useful to know them when reading existing code from others because not everyone use the same approach to do ajax requests (it can be also a third party library like axios). Using fetch will also help to introduce Promise e.g https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by reroth** [comment]
Thanks for pointing this out. We had been maintaining jquery despite evolving ES6 coding practices, as we use Bootstrap in another class. The latest version of Bootstrap now deprecates jquery, so will be working to eliminate jquery throughout the workbook. Ch1-3 will be revised this week. Really helpful comment!

**Comment by ThomasG77** [comment]
So, to escape for jQuery, this tool helps you make the switch e.g https://github.com/sachinchoolur/replace-jquery
You can also look at https://youmightnotneedjquery.com for equivalent to jQuery but manual, so on your own
